apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-action-template"
  annotations:
    github.com/project-slug: diegosantillan-coder/test-template
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: 